#!/usr/bin/env bash
set -ex

# Activate stitch env to solve argschema python version bug
source /opt/conda/etc/profile.d/conda.sh
conda activate convert_to_zarr

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u convert_to_omezarr.py "$@"
